# docker-compose.yml
services:
  # === KAFKA КЛАСТЕР (KRaft) ===
  kafka-1:
    image: confluentinc/cp-kafka:latest
    container_name: calculator-kafka-1
    hostname: kafka-1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ENABLE_KRAFT: "true"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093"
      KAFKA_LISTENERS: EXTERNAL://0.0.0.0:9092,INTERNAL://0.0.0.0:19092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://kafka-1:9092,INTERNAL://kafka-1:19092,CONTROLLER://kafka-1:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      CLUSTER_ID: my-cluster-id
    volumes:
      - kafka_data_1:/var/lib/kafka/data
    networks:
      - calculator-network
    healthcheck:
      test: >
        bash -c 'kafka-broker-api-versions --bootstrap-server localhost:9092 >/dev/null 2>&1 && exit 0 || exit 1'
      interval: 10s
      timeout: 10s
      retries: 15
      start_period: 30s

  kafka-2:
    image: confluentinc/cp-kafka:latest
    container_name: calculator-kafka-2
    hostname: kafka-2
    ports:
      - "9094:9094"
    environment:
      KAFKA_ENABLE_KRAFT: "true"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: 2
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093"
      KAFKA_LISTENERS: EXTERNAL://0.0.0.0:9094,INTERNAL://0.0.0.0:19094,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://kafka-2:9094,INTERNAL://kafka-2:19094,CONTROLLER://kafka-2:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      CLUSTER_ID: my-cluster-id
    volumes:
      - kafka_data_2:/var/lib/kafka/data
    networks:
      - calculator-network
    healthcheck:
      test: >
        bash -c 'kafka-broker-api-versions --bootstrap-server localhost:9094 >/dev/null 2>&1 && exit 0 || exit 1'
      interval: 10s
      timeout: 10s
      retries: 15
      start_period: 30s

  kafka-3:
    image: confluentinc/cp-kafka:latest
    container_name: calculator-kafka-3
    hostname: kafka-3
    ports:
      - "9096:9096"
    environment:
      KAFKA_ENABLE_KRAFT: "true"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: 3
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093"
      KAFKA_LISTENERS: EXTERNAL://0.0.0.0:9096,INTERNAL://0.0.0.0:19096,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://kafka-3:9096,INTERNAL://kafka-3:19096,CONTROLLER://kafka-3:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      CLUSTER_ID: my-cluster-id
    volumes:
      - kafka_data_3:/var/lib/kafka/data
    networks:
      - calculator-network
    healthcheck:
      test: >
        bash -c 'kafka-broker-api-versions --bootstrap-server localhost:9096 >/dev/null 2>&1 && exit 0 || exit 1'
      interval: 10s
      timeout: 10s
      retries: 15
      start_period: 30s

  # === REDIS ===
  redis:
    image: redis:7-alpine
    container_name: calculator-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - calculator-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  # === POSTGRES ===
  postgres:
    image: postgres:15-alpine
    container_name: calculator-postgres
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${TZ}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - calculator-network

  # === MIGRATE ===
  migrate:
    image: migrate/migrate:latest
    command: -path /migrations -database postgres://calculator:verydifficlutpassword@postgres:5432/calculator_db?sslmode=disable up
    volumes:
      - ./migrations:/migrations
    environment:
      POSTGRES_USER: calculator
      POSTGRES_PASSWORD: verydifficlutpassword
      POSTGRES_DB: calculator_db
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - calculator-network
    restart: "no"

  # === API СЕРВЕР ===
  api:
    build: .
    command: ./main
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      - KAFKA_BROKERS=kafka-1:9092,kafka-2:19092,kafka-3:19093
      - REDIS_ADDR=redis:6379
      - POSTGRES_DSN=host=postgres user=${POSTGRES_USER} password=${POSTGRES_PASSWORD} dbname=${POSTGRES_DB} port=5432 sslmode=disable
    depends_on:
      migrate:
        condition: service_completed_successfully
      kafka-1:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - calculator-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # === ВОРКЕРЫ ===
  worker1:
    build: .
    command: ./worker
    environment:
      - WORKER_PORT=8081
      - KAFKA_BROKERS=kafka-1:9092,kafka-2:19092,kafka-3:19093
      - REDIS_ADDR=redis:6379
      - POSTGRES_DSN=host=postgres user=${POSTGRES_USER} password=${POSTGRES_PASSWORD} dbname=${POSTGRES_DB} port=5432 sslmode=disable
    ports:
      - "8081:8081"
    depends_on:
      migrate:
        condition: service_completed_successfully
      api:
        condition: service_started
    networks:
      - calculator-network

  worker2:
    build: .
    command: ./worker
    environment:
      - WORKER_PORT=8082
      - KAFKA_BROKERS=kafka-1:9092,kafka-2:19092,kafka-3:19093
      - REDIS_ADDR=redis:6379
      - POSTGRES_DSN=host=postgres user=${POSTGRES_USER} password=${POSTGRES_PASSWORD} dbname=${POSTGRES_DB} port=5432 sslmode=disable
    ports:
      - "8082:8082"
    depends_on:
      migrate:
        condition: service_completed_successfully
      api:
        condition: service_started
    networks:
      - calculator-network

  worker3:
    build: .
    command: ./worker
    environment:
      - WORKER_PORT=8083
      - KAFKA_BROKERS=kafka-1:9092,kafka-2:19092,kafka-3:19093
      - REDIS_ADDR=redis:6379
      - POSTGRES_DSN=host=postgres user=${POSTGRES_USER} password=${POSTGRES_PASSWORD} dbname=${POSTGRES_DB} port=5432 sslmode=disable
    ports:
      - "8083:8083"
    depends_on:
      migrate:
        condition: service_completed_successfully
      api:
        condition: service_started
    networks:
      - calculator-network

volumes:
  postgres_data:
  kafka_data_1:
  kafka_data_2:
  kafka_data_3:
  redis_data:

networks:
  calculator-network:
    driver: bridge